language: node_js
node_js:
  - "0.12"
before_install:
  - "npm install -g bower"
  - "bower install"
  - "ln -s .. bower_components/yarn-elements"
  - "npm install -g web-component-tester"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "wct"

